<script setup>
import { ref, computed } from 'vue'
import { clubApi } from '../../api/club'
import { useUser } from '../../stores/user'
import { usePage, action } from '../../utils/ui'
import PageHeader from '../../components/PageHeader.vue'
const store = useUser(), rows = ref([]), search = ref(''), selected = ref(null), drawer = ref(false), joining = ref(false)
const { loading, error, load } = usePage(async () => { rows.value = await clubApi.list() })
const filtered = computed(() => rows.value.filter(r => `${r.clubName}${r.clubDesc}${r.teaName}`.includes(search.value)))
async function detail(row) { await action(async () => { selected.value = await clubApi.detail(row.clubId); drawer.value = true }, '') }
async function join(row) { joining.value = true; await action(async () => { await clubApi.join(row.clubId) }, '申请已提交，请在个人中心查看审批进度'); joining.value = false }
</script>
<template><PageHeader title="社团广场" subtitle="每一种热爱，都能在这里找到回响。"><el-button @click="load" :loading="loading">刷新广场</el-button></PageHeader><section class="campus-banner"><div><span class="eyebrow">FIND YOUR PEOPLE</span><h2>课本之外，<br>还有无限可能。</h2><p>探索校园社团，开启一段新的同行。</p><router-link v-if="store.user?.userType === 'student'" to="/club/create">和朋友一起，创建社团 ↗</router-link></div><div class="banner-art" aria-hidden="true"><div class="big-flower">✳</div><span>相遇 / 热爱 / 成长</span></div><div class="banner-stat"><strong>{{ rows.length.toString().padStart(2, '0') }}</strong><span>个社团，等待相遇</span></div></section><div class="section-row club-toolbar"><h2>探索全部社团 <span class="count">{{ filtered.length }}</span></h2><el-input v-model="search" placeholder="搜索社团 / 指导教师" clearable style="max-width:300px" aria-label="搜索社团" /></div><el-alert v-if="error" :title="error" type="error" /><div v-loading="loading" class="club-grid"><article v-for="(row, i) in filtered" :key="row.clubId" class="club-card"><div class="club-cover" :class="`cover-${i % 3}`"><span class="cover-mark">{{ row.clubName.slice(0, 1) }}</span><span class="cover-caption">CAMPUS COMMUNITY</span><span class="cover-index">{{ String(i + 1).padStart(2, '0') }}</span></div><div class="club-card-body"><div class="section-row"><h3>{{ row.clubName }}</h3><el-tag type="success" round>运营中</el-tag></div><p class="club-description">{{ row.clubDesc }}</p><div class="club-meta"><span>指导教师 · {{ row.teaName }}</span><span>{{ row.memberCount }} 位社员</span></div><div class="club-card-actions"><el-button @click="detail(row)">了解社团 ↗</el-button><el-button v-if="store.user?.userType === 'student' && !store.clubId" type="primary" :loading="joining" @click="join(row)">申请加入</el-button></div></div></article></div><el-empty v-if="!loading && !filtered.length" description="还没有匹配的社团" /><el-drawer v-model="drawer" :title="selected?.clubName" size="min(560px, 100vw)"><template v-if="selected"><p class="body-copy">{{ selected.clubDesc }}</p><div class="info-strip"><span>指导教师 {{ selected.teaName }}</span><span>{{ selected.memberCount }} 位在职社员</span></div><p class="muted">成立于 {{ selected.clubCreateTime }}</p><h3>社团公告</h3><article v-for="notice in selected.notices" :key="notice.noticeId" class="notice-item"><h4>{{ notice.noticeTitle }}</h4><p class="body-copy">{{ notice.noticeContent }}</p><time>{{ notice.publishTime }} · {{ notice.publishName }}</time></article><el-empty v-if="!selected.notices.length" description="暂无公告" /></template></el-drawer></template>
