<script setup>
import { ref } from 'vue'
import { teacherApi } from '../../api/teacher'
import { usePage, action, confirm } from '../../utils/ui'
import { memberColumns, activityColumns } from '../../utils/columns'
import PageHeader from '../../components/PageHeader.vue'
import DataTable from '../../components/DataTable.vue'
import AuditPanel from '../../components/AuditPanel.vue'
const creates = ref([]), dissolves = ref([]), activities = ref([]), club = ref(null), busy = ref(false)
const { loading, error, load } = usePage(async () => { [creates.value, dissolves.value, activities.value, club.value] = await Promise.all([teacherApi.creates(), teacherApi.dissolves(), teacherApi.activities(), teacherApi.club()]) })
async function auditActivity(row, result) { busy.value = true; await action(async () => { await confirm(`确认${result === 'agree' ? '同意' : '驳回'}「${row.actName}」？`); await teacherApi.audit('activities', row.actId, result); await load() }); busy.value = false }
</script>
<template><PageHeader title="教师工作台" subtitle="陪伴社团成长，让每一份热爱有方向。" eyebrow="FACULTY WORKBENCH"><el-button @click="load" :loading="loading">刷新工作台</el-button></PageHeader><el-alert v-if="error" :title="error" type="error" /><div class="stats-grid"><div class="stat-card"><span>指导社团</span><strong class="text-stat">{{ club?.clubName || '暂未绑定' }}</strong></div><div class="stat-card"><span>待审批活动</span><strong>{{ activities.length }}<small>项</small></strong></div><div class="stat-card"><span>待审建团</span><strong>{{ creates.filter(r => r.finalStatus === 'pending' && r.teaAuditStatus === 'pending').length }}<small>份</small></strong></div><div class="stat-card"><span>待审解散</span><strong>{{ dissolves.filter(r => r.finalStatus === 'pending' && r.teaAuditStatus === 'pending').length }}<small>份</small></strong></div></div><section v-loading="loading"><el-tabs><el-tab-pane label="活动审批"><div class="panel"><DataTable :rows="activities" :columns="activityColumns" empty="暂无待审批活动"><template #default="{ row }"><el-button type="primary" size="small" :disabled="busy" @click="auditActivity(row, 'agree')">同意</el-button><el-button type="danger" plain size="small" :disabled="busy" @click="auditActivity(row, 'reject')">驳回</el-button></template></DataTable><article v-for="row in activities" :key="row.actId" class="notice-item"><h4>{{ row.actName }} · 活动介绍</h4><p class="body-copy">{{ row.actDesc }}</p></article></div></el-tab-pane><el-tab-pane label="建团审批"><AuditPanel :rows="creates" side="tea" :audit="(r, result) => teacherApi.audit('create-applies', r.createApplyId, result)" @changed="load" /></el-tab-pane><el-tab-pane label="解散审批"><AuditPanel :rows="dissolves" side="tea" kind="dissolve" :audit="(r, result) => teacherApi.audit('dissolve-applies', r.dissolveApplyId, result)" @changed="load" /></el-tab-pane><el-tab-pane label="所辖社团"><section v-if="club" class="panel"><h2>{{ club.clubName }}</h2><p class="body-copy">{{ club.clubDesc }}</p><h3 class="section-title">在职社员</h3><DataTable :rows="club.members" :columns="memberColumns" /><h3 class="section-title">活动记录</h3><DataTable :rows="club.activities" :columns="activityColumns" /><h3 class="section-title">有效公告</h3><article v-for="n in club.notices" :key="n.noticeId" class="notice-item"><h4>{{ n.noticeTitle }}</h4><p class="body-copy">{{ n.noticeContent }}</p><time>{{ n.publishTime }}</time></article></section><el-empty v-else description="当前没有指导的社团" /></el-tab-pane></el-tabs></section></template>
